import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import ProductCard from "../components/ProductCard";
import NavBar from "../components/NavBar";

const Home: NextPage = () => {
  const { data } = trpc.product.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="mx-auto max-w-2xl sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8 p-3">
        <h2 className="text-2xl font-bold tracking-tight text-gray-900">Productos:</h2>
        <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
          {data?.map(product =>
            <ProductCard key={product.id}
              id={product.id}
              name={product.name}
              slug={product.slug}
              description={product.description}
              inventory={product.inventory}
              price={Number(product.price)}
            />
          ) ?? <span>Cargando...</span>}
        </div>
      </div>
    </>
  );
}

export default Home;
